spring:
    datasource:
        url: jdbc:mysql://localhost:3306/activiti6?serverTimeZone=UTC&nullCatalogMeansCurrent=true
        username: root
        password: zzde123#

    redis:
        host: localhost
        port: 6379
        database: 1

mybatis:
    mapper-locations: classpath:mybatis/mapper/*Mapper.xml

