spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: test
        password: test1234
        virtualHost: jack

    cloud:
        stream:
            bindings:
                organization:
                    destination: organization