server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                    uri: file:///Users/zhouzhengde/Desktop/repos/spring_cloud_config_git_repo
                    search-paths: spring_microservices_in_action_20190427/config
                    username:
                    password: